apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turbo-paja
  namespace: aplicacioncita
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
