apiVersion: v1
kind: Service
metadata:
  name: backend-node-port
  namespace: aplicacioncita
spec:
  type: NodePort
  selector:
    aplicacion: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200
