apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-load-balancer
  namespace: aplicacioncita
spec:
  ingressClassName: traefik
  rules:
    - host: backend.aplicacioncita.com
      http: 
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-backend
                port:
                  number: 80
